name: Bale Inventory Bot

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  inventory-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/386194470839/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "bale-reminder@bale-reminder-bot.iam.gserviceaccount.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Test OKCS connection
        run: |
         python - <<'PY'
         import requests
         import traceback

         print("=== OKCS CONNECTION TEST ===")

         try:
             s = requests.Session()
             s.trust_env = False

             print("Connecting to https://sap.okcs.com ...")

             r = s.get(
                  "https://sap.okcs.com",
                  timeout=20
             )

             print("STATUS:", r.status_code)
             print("RESPONSE:", r.text[:500])

         except Exception as e:
             print("ERROR TYPE:", type(e).__name__)
             print("ERROR:", str(e))
             print("=== FULL TRACEBACK ===")
             traceback.print_exc()
             raise
         PY
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run inventory bot
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          OKCS_USERNAME: ${{ secrets.OKCS_USERNAME }}
          OKCS_PASSWORD: ${{ secrets.OKCS_PASSWORD }}
        run: python bot.py
